In [21]:
import pandas as pd
import numpy as np

In [7]:
data=pd.read_csv('train.csv',usecols=['Survived','Pclass','Age','SibSp','Parch','Fare'])
data.head()

   Survived  Pclass   Age  SibSp  Parch     Fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
4         0       3  35.0      0      0   8.0500

In [8]:
data.shape

(891, 6)

In [9]:
data.dropna(subset=['Age'],inplace=True)

In [10]:
data.isna().sum()

Survived    0
Pclass      0
Age         0
SibSp       0
Parch       0
Fare        0
dtype: int64

In [13]:
from sklearn.model_selection import train_test_split,cross_val_score

X_train,X_test,y_train,y_test=train_test_split(data.drop(columns=['Survived']),data['Survived'],test_size=0.2,random_state=42)
X_train.shape,X_test.shape

((571, 5), (143, 5))

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [18]:
lr=LogisticRegression()
lr.fit(X_train,y_train)

y_pred=lr.predict(X_test)

score=accuracy_score(y_test,y_pred)
score

0.6993006993006993

In [22]:
np.mean(cross_val_score(LogisticRegression(),data.drop(columns=['Survived']),data['Survived'],scoring='accuracy',cv=10))

np.float64(0.6991001564945227)

In [24]:
# Feature Contruction

data['Family']=data['SibSp']+data['Parch']+1

In [25]:
data.head()

   Survived  Pclass   Age  SibSp  Parch     Fare  Family
0         0       3  22.0      1      0   7.2500       2
1         1       1  38.0      1      0  71.2833       2
2         1       3  26.0      0      0   7.9250       1
3         1       1  35.0      1      0  53.1000       2
4         0       3  35.0      0      0   8.0500       1

In [26]:
data.drop(columns=['SibSp','Parch'],inplace=True)

In [27]:
data['Family']=np.where(data['Family']>1,1,0)

In [28]:
data.head()

   Survived  Pclass   Age     Fare  Family
0         0       3  22.0   7.2500       1
1         1       1  38.0  71.2833       1
2         1       3  26.0   7.9250       0
3         1       1  35.0  53.1000       1
4         0       3  35.0   8.0500       0

In [29]:
X_train,X_test,y_train,y_test=train_test_split(data.drop(columns=['Survived']),data['Survived'],test_size=0.2,random_state=42)
X_train.shape,X_test.shape

((571, 4), (143, 4))

In [30]:
lr=LogisticRegression()
lr.fit(X_train,y_train)

y_pred=lr.predict(X_test)

score=accuracy_score(y_test,y_pred)
score

0.6923076923076923

In [31]:
np.mean(cross_val_score(LogisticRegression(),data.drop(columns=['Survived']),data['Survived'],scoring='accuracy',cv=10))

np.float64(0.7089006259780908)

In [32]:
# Feature splitting

In [33]:
data=pd.read_csv('train.csv')
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [56]:
data['Title']=data.loc[:,'Name'].str.split(",",expand=True)[1].str.split('.',expand=True)[0]

In [58]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr