In [7]:
import pandas as pd
import numpy as np

In [16]:
data=pd.read_json(r"train.json").head()
data.head()

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2  20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3  22213       indian                [water, vegetable oil, wheat, salt]
4  13162       indian  [black pepper, shallots, cornflour, cayenne pe...

In [5]:
data.shape

(39774, 3)

In [14]:
# typ -> series,frame
pd.read_json(r"train.json",typ='frame').head()

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2  20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3  22213       indian                [water, vegetable oil, wheat, salt]
4  13162       indian  [black pepper, shallots, cornflour, cayenne pe...

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           5 non-null      int64
 1   cuisine      5 non-null      object
 2   ingredients  5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [24]:
# dtype and convert_dates=True -> auto convert dates 
pd.read_json(r"train.json",dtype={'id':"int32"}).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39774 entries, 0 to 39773
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           39774 non-null  int32
 1   cuisine      39774 non-null  object
 2   ingredients  39774 non-null  object
dtypes: int32(1), object(2)
memory usage: 777.0+ KB

In [28]:
# encoding and nrows
pd.read_json(r"train.json",encoding='utf-8').head()

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2  20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3  22213       indian                [water, vegetable oil, wheat, salt]
4  13162       indian  [black pepper, shallots, cornflour, cayenne pe...

In [34]:
# compression
pd.read_json(r"train.json",encoding='utf-8',compression="zip").head()

In [36]:
# chunksize
# pd.read_json(r"train.json",encoding='utf-8',chunksize=1000).head()