In [17]:
import pandas as pd
import numpy as np

In [78]:
data=pd.read_csv(r"Collect Data/jester_items.tsv",sep="\t",names=['no','joke'],usecols=[0,1])
data.head()

   no                                               joke
0  1:  A man visits the doctor. The doctor says, "I h...
1  2:  This couple had an excellent relationship goin...
2  3:  Q. What's 200 feet long and has 4 teeth? A. Th...
3  4:  Q. What's the difference between a man and a t...
4  5:  Q. What's O. J. Simpson's web address? A. Slas...

In [38]:
data=pd.read_csv(r"Collect Data/jester_items.tsv",sep='\t',nrows=1000)
data.shape

(148, 2)

In [42]:
# encoding
pd.read_csv(r"Collect Data/jester_items.tsv",sep='\t',nrows=1000,encoding='utf-8',names=['no','joke'],usecols=[1],erro).head()

                                                joke
0  A man visits the doctor. The doctor says, "I h...
1  This couple had an excellent relationship goin...
2  Q. What's 200 feet long and has 4 teeth? A. Th...
3  Q. What's the difference between a man and a t...
4  Q. What's O. J. Simpson's web address? A. Slas...

In [45]:
# on bad lines
pd.read_csv(r"Collect Data/jester_items.tsv",sep='\t',nrows=1000,encoding='utf-8',names=['no','joke'],usecols=[1],on_bad_lines='skip').head()

                                                joke
0  A man visits the doctor. The doctor says, "I h...
1  This couple had an excellent relationship goin...
2  Q. What's 200 feet long and has 4 teeth? A. Th...
3  Q. What's the difference between a man and a t...
4  Q. What's O. J. Simpson's web address? A. Slas...

In [49]:
# dtypes
pd.read_csv(r"Collect Data/jester_items.tsv",sep='\t',nrows=1000,encoding='utf-8',names=['no','joke'],dtype={0:'category'},on_bad_lines='skip').head()

   no                                               joke
0  1:  A man visits the doctor. The doctor says, "I h...
1  2:  This couple had an excellent relationship goin...
2  3:  Q. What's 200 feet long and has 4 teeth? A. Th...
3  4:  Q. What's the difference between a man and a t...
4  5:  Q. What's O. J. Simpson's web address? A. Slas...

In [63]:
# parse_dates
pd.read_csv(r"E:\Datasets\sales_data_large .csv",parse_dates=['Date']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         120 non-null    datetime64[ns]
 1   Product      120 non-null    object
 2   Units Sold   120 non-null    int64
 3   Revenue      120 non-null    int64
 4   Region       120 non-null    object
 5   Salesperson  120 non-null    object
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 5.8+ KB

In [69]:
# converters
def rename(s):
    if s=='V Kohli':
        return "Virat"
    else:
        return s

data=pd.read_csv(r"E:\Datasets\batter.csv",converters={"batter":rename},na_values='V Kohli')
data.head()

      batter  runs        avg  strike_rate
0      Virat  6634  36.251366   125.977972
1   S Dhawan  6244  34.882682   122.840842
2  DA Warner  5883  41.429577   136.401577
3  RG Sharma  5881  30.314433   126.964594
4   SK Raina  5536  32.374269   132.535312

In [71]:
data=pd.read_csv(r"E:\Datasets\batter.csv",na_values='V Kohli')
data.head()

      batter  runs        avg  strike_rate
0        NaN  6634  36.251366   125.977972
1   S Dhawan  6244  34.882682   122.840842
2  DA Warner  5883  41.429577   136.401577
3  RG Sharma  5881  30.314433   126.964594
4   SK Raina  5536  32.374269   132.535312

In [72]:
chunks = pd.read_csv(r"E:\Datasets\batter.csv", chunksize=200)

In [73]:
for i in chunks:
    print(i.shape)

(200, 4)
(200, 4)
(200, 4)
(5, 4)

In [74]:
data.shape

(605, 4)