In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

In [5]:
data=sns.load_dataset('titanic')
data=data[['age','fare','sibsp','parch','survived']].copy()

In [6]:
data.head()

    age     fare  sibsp  parch  survived
0  22.0   7.2500      1      0         0
1  38.0  71.2833      1      0         1
2  26.0   7.9250      0      0         1
3  35.0  53.1000      1      0         1
4  35.0   8.0500      0      0         0

In [7]:
data.dropna(inplace=True)

In [9]:
data['family'] = data['sibsp'] + data['parch']

In [10]:
data.head()

    age     fare  sibsp  parch  survived  family
0  22.0   7.2500      1      0         0       1
1  38.0  71.2833      1      0         1       1
2  26.0   7.9250      0      0         1       0
3  35.0  53.1000      1      0         1       1
4  35.0   8.0500      0      0         0       0

In [12]:
data.drop(columns=['sibsp','parch'],inplace=True)

In [13]:
data.head()

    age     fare  survived  family
0  22.0   7.2500         0       1
1  38.0  71.2833         1       1
2  26.0   7.9250         1       0
3  35.0  53.1000         1       1
4  35.0   8.0500         0       0

In [15]:
X = data.drop(columns=['survived'])
y = data['survived']

In [17]:
from sklearn.model_selection import train_test_split,cross_val_score

In [18]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape,X_test.shape

((571, 3), (143, 3))

In [20]:
# Without binarization

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
clf = DecisionTreeClassifier()

clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

accuracy_score(y_test,y_pred)

0.6223776223776224

In [21]:
np.mean(cross_val_score(DecisionTreeClassifier(),X,y,cv=10,scoring='accuracy'))

np.float64(0.6429186228482003)

In [22]:
from sklearn.preprocessing import Binarizer

In [24]:
from sklearn.compose import ColumnTransformer
trf = ColumnTransformer([
    ('bin',Binarizer(copy=False),['family'])
],remainder='passthrough')

In [25]:
X_train_trf = trf.fit_transform(X_train)
X_test_trf = trf.transform(X_test)

In [26]:
pd.DataFrame(X_train_trf,columns=['family','Age','Fare']).head()

   family   Age     Fare
0     1.0  31.0  20.5250
1     1.0  26.0  14.4542
2     1.0  30.0  16.1000
3     0.0  33.0   7.7750
4     0.0  25.0  13.0000

In [27]:
clf = DecisionTreeClassifier()
clf.fit(X_train_trf,y_train)
y_pred2 = clf.predict(X_test_trf)

accuracy_score(y_test,y_pred2)

0.5874125874125874

In [28]:
X_trf = trf.fit_transform(X)
np.mean(cross_val_score(DecisionTreeClassifier(),X_trf,y,cv=10,scoring='accuracy'))

np.float64(0.6261737089201878)

In [ ]:
# some time not works