In [1]:
import numpy as np
import pandas as pd

In [9]:
date = pd.read_csv('orders.csv',parse_dates=['date'])
time = pd.read_csv('messages.csv')

In [10]:
date.head()

        date  product_id  city_id  orders
0 2019-12-10        5628       25       3
1 2018-08-15        3646       14     157
2 2018-10-23        1859       25       1
3 2019-08-17        7292       25       1
4 2019-01-06        4344       25       3

In [11]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [12]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [13]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [14]:
time['date']=pd.to_datetime(time['date'])

In [15]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [16]:
date.head()

        date  product_id  city_id  orders
0 2019-12-10        5628       25       3
1 2018-08-15        3646       14     157
2 2018-10-23        1859       25       1
3 2019-08-17        7292       25       1
4 2019-01-06        4344       25       3

In [19]:
date['date'].dt.year.head(1)

0    2019
Name: date, dtype: int32

In [20]:
date['date'].dt.month.head(1)

0    12
Name: date, dtype: int32

In [23]:
date['date'].dt.month_name().head(1)

0    December
Name: date, dtype: object

In [24]:
date['date'].dt.day.head(1)

0    10
Name: date, dtype: int32

In [25]:
date['date'].dt.dayofweek.head(1)

0    1
Name: date, dtype: int32

In [26]:
date['date'].dt.day_name().head(1)

0    Tuesday
Name: date, dtype: object

In [30]:
date['date'].dt.date

0      2019-12-10
1      2018-08-15
2      2018-10-23
3      2019-08-17
4      2019-01-06
          ...
995    2018-10-08
996    2018-12-06
997    2019-05-07
998    2019-03-03
999    2019-10-15
Name: date, Length: 1000, dtype: object

In [31]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

        date  quarter
0 2019-12-10        4
1 2018-08-15        3
2 2018-10-23        4
3 2019-08-17        3
4 2019-01-06        1

In [32]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

        date  quarter  semester
0 2019-12-10        4         2
1 2018-08-15        3         2
2 2018-10-23        4         2
3 2019-08-17        3         2
4 2019-01-06        1         1

In [33]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 7, 4, 18, 22, 40, 145992)

In [34]:
today - date['date']

0     2398 days 18:22:40.145992
1     2880 days 18:22:40.145992
2     2811 days 18:22:40.145992
3     2513 days 18:22:40.145992
4     2736 days 18:22:40.145992
                 ...
995   2826 days 18:22:40.145992
996   2767 days 18:22:40.145992
997   2615 days 18:22:40.145992
998   2680 days 18:22:40.145992
999   2454 days 18:22:40.145992
Name: date, Length: 1000, dtype: timedelta64[ns]

In [35]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [36]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [37]:
(today - time['date'])/np.timedelta64(1,'m')

0      6.602013e+06
1      6.406243e+06
2      7.106042e+06
3      6.100912e+06
4      6.672672e+06
           ...
995    7.522173e+06
996    6.544509e+06
997    7.214086e+06
998    7.381129e+06
999    6.332818e+06
Name: date, Length: 1000, dtype: float64